//
//  FlagsBank.swift
//  Flags
//
//  Created by Руслан Кукса on 1/22/19.
//  Copyright © 2019 Ruslan Kuksa. All rights reserved.
//

import Foundation

struct FlagsBank {
    var flagsLevel1 = [Countries]()
    var flagsLevel2 = [Countries]()
    var flagsLevel3 = [Countries]()
    var flagsLevel4 = [Countries]()
    var flagsLevel5 = [Countries]()
    var flagsLevel6 = [Countries]()
    var flagsLevel7 = [Countries]()
    var flagsLevel8 = [Countries]()
    var flagsLevel9 = [Countries]()
    var flagsLevel10 = [Countries]()
    
    
    var flagsBank = [[Countries]()]
    
    init() {
        flagsLevel1.append(Countries(countryName: "Spain", imageName: "es"))
        flagsLevel1.append(Countries(countryName: "United States", imageName: "us"))
        flagsLevel1.append(Countries(countryName: "Japan", imageName: "jp"))
        flagsLevel1.append(Countries(countryName: "France", imageName: "fr"))
        flagsLevel1.append(Countries(countryName: "Brazil", imageName: "br"))
        flagsLevel1.append(Countries(countryName: "India", imageName: "in"))
        flagsLevel1.append(Countries(countryName: "China", imageName: "cn"))
        flagsLevel1.append(Countries(countryName: "Germany", imageName: "de"))
        flagsLevel1.append(Countries(countryName: "Canada", imageName: "ca"))
        flagsLevel1.append(Countries(countryName: "Italy", imageName: "it"))
        flagsLevel1.append(Countries(countryName: "Great Britain", imageName: "gb"))
        flagsLevel1.append(Countries(countryName: "Uruguay", imageName: "uy"))
        flagsLevel1.append(Countries(countryName: "Russia", imageName: "ru"))
        flagsLevel1.append(Countries(countryName: "Argentina", imageName: "ar"))
        flagsLevel1.append(Countries(countryName: "Portugal", imageName: "pt"))
        flagsLevel1.append(Countries(countryName: "Norway", imageName: "no"))
        flagsLevel1.append(Countries(countryName: "Sweden", imageName: "se"))
        flagsLevel1.append(Countries(countryName: "Saudi Arabia", imageName: "sa"))
        flagsLevel1.append(Countries(countryName: "Switzerland", imageName: "ch"))
        flagsLevel1.append(Countries(countryName: "South Korea", imageName: "kr"))
        
        flagsLevel2.append(Countries(countryName: "Luxembourg", imageName: "lu"))
        flagsLevel2.append(Countries(countryName: "Czech Republic", imageName: "cz"))
        flagsLevel2.append(Countries(countryName: "Cuba", imageName: "cu"))
        flagsLevel2.append(Countries(countryName: "Finland", imageName: "fi"))
        flagsLevel2.append(Countries(countryName: "Belgium", imageName: "be"))
        flagsLevel2.append(Countries(countryName: "Tunisia", imageName: "tn"))
        flagsLevel2.append(Countries(countryName: "Iceland", imageName: "is"))
        flagsLevel2.append(Countries(countryName: "New Zeland", imageName: "nz"))
        flagsLevel2.append(Countries(countryName: "Australia", imageName: "au"))
        flagsLevel2.append(Countries(countryName: "Netherlands", imageName: "nl"))
        flagsLevel2.append(Countries(countryName: "Mexico", imageName: "mx"))
        flagsLevel2.append(Countries(countryName: "Thailand", imageName: "th"))
        flagsLevel2.append(Countries(countryName: "Ireland", imageName: "ie"))
        flagsLevel2.append(Countries(countryName: "Egypt", imageName: "eg"))
        flagsLevel2.append(Countries(countryName: "Denmark", imageName: "dk"))
        flagsLevel2.append(Countries(countryName: "Croatia", imageName: "hr"))
        flagsLevel2.append(Countries(countryName: "Greece", imageName: "gr"))
        flagsLevel2.append(Countries(countryName: "Israel", imageName: "il"))
        flagsLevel2.append(Countries(countryName: "Iran", imageName: "ir"))
        flagsLevel2.append(Countries(countryName: "Romania", imageName: "ro"))
        
        flagsLevel3.append(Countries(countryName: "United Arab Emirates", imageName: "ae"))
        flagsLevel3.append(Countries(countryName: "Latvia", imageName: "lv"))
        flagsLevel3.append(Countries(countryName: "Belarus", imageName: "by"))
        flagsLevel3.append(Countries(countryName: "Cyprus", imageName: "cy"))
        flagsLevel3.append(Countries(countryName: "Indonesia", imageName: "id"))
        flagsLevel3.append(Countries(countryName: "North Korea", imageName: "kp"))
        flagsLevel3.append(Countries(countryName: "Poland", imageName: "pl"))
        flagsLevel3.append(Countries(countryName: "Morocco", imageName: "ma"))
        flagsLevel3.append(Countries(countryName: "Colombia", imageName: "co"))
        flagsLevel3.append(Countries(countryName: "Austria", imageName: "at"))
        flagsLevel3.append(Countries(countryName: "Turkey", imageName: "tr"))
        flagsLevel3.append(Countries(countryName: "Singapore", imageName: "sg"))
        flagsLevel3.append(Countries(countryName: "Paraguay", imageName: "py"))
        flagsLevel3.append(Countries(countryName: "Vietnam", imageName: "vn"))
        flagsLevel3.append(Countries(countryName: "Ukraine", imageName: "ua"))
        flagsLevel3.append(Countries(countryName: "Makedonia", imageName: "mk"))
        flagsLevel3.append(Countries(countryName: "Malaysia", imageName: "my"))
        flagsLevel3.append(Countries(countryName: "Iraq", imageName: "iq"))
        flagsLevel3.append(Countries(countryName: "Venezuela", imageName: "ve"))
        flagsLevel3.append(Countries(countryName: "Vatican", imageName: "va"))
        
        flagsLevel4.append(Countries(countryName: "Bosnia and Herzegovina", imageName: "ba"))
        flagsLevel4.append(Countries(countryName: "Cameroon", imageName: "cm"))
        flagsLevel4.append(Countries(countryName: "Monaco", imageName: "mc"))
        flagsLevel4.append(Countries(countryName: "Georgia", imageName: "ge"))
        flagsLevel4.append(Countries(countryName: "Hungary", imageName: "hu"))
        flagsLevel4.append(Countries(countryName: "Senegal", imageName: "sn"))
        flagsLevel4.append(Countries(countryName: "Sudan", imageName: "sd"))
        flagsLevel4.append(Countries(countryName: "Syria", imageName: "sy"))
        flagsLevel4.append(Countries(countryName: "South Africa", imageName: "za"))
        flagsLevel4.append(Countries(countryName: "Slovakia", imageName: "sk"))
        flagsLevel4.append(Countries(countryName: "Slovenia", imageName: "si"))
        flagsLevel4.append(Countries(countryName: "Serbia", imageName: "rs"))
        flagsLevel4.append(Countries(countryName: "Peru", imageName: "pe"))
        flagsLevel4.append(Countries(countryName: "Kenya", imageName: "ke"))
        flagsLevel4.append(Countries(countryName: "Litva", imageName: "lt"))
        flagsLevel4.append(Countries(countryName: "Qatar", imageName: "qa"))
        flagsLevel4.append(Countries(countryName: "Azerbaijan", imageName: "az"))
        flagsLevel4.append(Countries(countryName: "Bulgaria", imageName: "bg"))
        flagsLevel4.append(Countries(countryName: "Algeria", imageName: "dz"))
        flagsLevel4.append(Countries(countryName: "Afghanistan", imageName: "af"))
        
        flagsLevel5.append(Countries(countryName: "Andorra", imageName: "ad"))
        flagsLevel5.append(Countries(countryName: "Bolivia", imageName: "bo"))
        flagsLevel5.append(Countries(countryName: "Ecuador", imageName: "ec"))
        flagsLevel5.append(Countries(countryName: "Honduras", imageName: "hn"))
        flagsLevel5.append(Countries(countryName: "Nicaragua", imageName: "ni"))
        flagsLevel5.append(Countries(countryName: "Philippines", imageName: "ph"))
        flagsLevel5.append(Countries(countryName: "Panama", imageName: "pa"))
        flagsLevel5.append(Countries(countryName: "Nigeria", imageName: "ng"))
        flagsLevel5.append(Countries(countryName: "Moldova", imageName: "md"))
        flagsLevel5.append(Countries(countryName: "Jamaica", imageName: "jm"))
        flagsLevel5.append(Countries(countryName: "Dominican Republic", imageName: "do"))
        flagsLevel5.append(Countries(countryName: "Pakistan", imageName: "pk"))
        flagsLevel5.append(Countries(countryName: "El Salvador", imageName: "sv"))
        flagsLevel5.append(Countries(countryName: "Zambia", imageName: "zm"))
        flagsLevel5.append(Countries(countryName: "Taiwan", imageName: "tw"))
        flagsLevel5.append(Countries(countryName: "Samoa", imageName: "ws"))
        flagsLevel5.append(Countries(countryName: "Liechtenstein", imageName: "li"))
        flagsLevel5.append(Countries(countryName: "Armenia", imageName: "am"))
        flagsLevel5.append(Countries(countryName: "Scotland", imageName: "scot"))
        flagsLevel5.append(Countries(countryName: "Mali", imageName: "ml"))
        
        flagsLevel6.append(Countries(countryName: "Bangladesh", imageName: "bd"))
        flagsLevel6.append(Countries(countryName: "Cambodia", imageName: "kh"))
        flagsLevel6.append(Countries(countryName: "Barbados", imageName: "bb"))
        flagsLevel6.append(Countries(countryName: "Bhutan", imageName: "bt"))
        flagsLevel6.append(Countries(countryName: "Ghana", imageName: "gh"))
        flagsLevel6.append(Countries(countryName: "Kazakhstan", imageName: "kz"))
        flagsLevel6.append(Countries(countryName: "Costa Rica", imageName: "cr"))
        flagsLevel6.append(Countries(countryName: "Albania", imageName: "al"))
        flagsLevel6.append(Countries(countryName: "Haiti", imageName: "ht"))
        flagsLevel6.append(Countries(countryName: "Jordan", imageName: "jo"))
        flagsLevel6.append(Countries(countryName: "Kuwait", imageName: "kw"))
        flagsLevel6.append(Countries(countryName: "Mongolia", imageName: "mn"))
        flagsLevel6.append(Countries(countryName: "Malta", imageName: "mt"))
        flagsLevel6.append(Countries(countryName: "Libya", imageName: "ly"))
        flagsLevel6.append(Countries(countryName: "Kyrgyzstan", imageName: "kg"))
        flagsLevel6.append(Countries(countryName: "Yemen", imageName: "ye"))
        flagsLevel6.append(Countries(countryName: "Oman", imageName: "om"))
        flagsLevel6.append(Countries(countryName: "Papua New Guinea", imageName: "pg"))
        flagsLevel6.append(Countries(countryName: "Tanzania", imageName: "tz"))
        flagsLevel6.append(Countries(countryName: "Uzbekistan", imageName: "uz"))
        
        flagsLevel7.append(Countries(countryName: "Zimbabwe", imageName: "zw"))
        flagsLevel7.append(Countries(countryName: "Uganda", imageName: "ug"))
        flagsLevel7.append(Countries(countryName: "Togo", imageName: "tg"))
        flagsLevel7.append(Countries(countryName: "Suriname", imageName: "sr"))
        flagsLevel7.append(Countries(countryName: "Sri Lanka", imageName: "lk"))
        flagsLevel7.append(Countries(countryName: "South Sudan", imageName: "ss"))
        flagsLevel7.append(Countries(countryName: "Niger", imageName: "ne"))
        flagsLevel7.append(Countries(countryName: "Namibia", imageName: "na"))
        flagsLevel7.append(Countries(countryName: "Trinidad and Tobago", imageName: "tt"))
        flagsLevel7.append(Countries(countryName: "Madagascar", imageName: "mg"))
        flagsLevel7.append(Countries(countryName: "Lebanon", imageName: "lb"))
        flagsLevel7.append(Countries(countryName: "Liberia", imageName: "lr"))
        flagsLevel7.append(Countries(countryName: "Guinea", imageName: "gn"))
        flagsLevel7.append(Countries(countryName: "Democratic Republic of the Congo", imageName: "cd"))
        flagsLevel7.append(Countries(countryName: "Republic of the Congo", imageName: "cg"))
        flagsLevel7.append(Countries(countryName: "Chad", imageName: "td"))
        flagsLevel7.append(Countries(countryName: "Angola", imageName: "ao"))
        flagsLevel7.append(Countries(countryName: "Bahamas", imageName: "bs"))
        flagsLevel7.append(Countries(countryName: "Bahrain", imageName: "bh"))
        flagsLevel7.append(Countries(countryName: "Brunei", imageName: "bn"))
        
        flagsLevel8.append(Countries(countryName: "Djibouti", imageName: "dj"))
        flagsLevel8.append(Countries(countryName: "Equatorial Guinea", imageName: "gq"))
        flagsLevel8.append(Countries(countryName: "Ethiopia", imageName: "et"))
        flagsLevel8.append(Countries(countryName: "Fiji", imageName: "fj"))
        flagsLevel8.append(Countries(countryName: "Gabon", imageName: "ga"))
        flagsLevel8.append(Countries(countryName: "Kiribati", imageName: "ki"))
        flagsLevel8.append(Countries(countryName: "Botswana", imageName: "bw"))
        flagsLevel8.append(Countries(countryName: "Central African Republic", imageName: "cf"))
        flagsLevel8.append(Countries(countryName: "Burundi", imageName: "bi"))
        flagsLevel8.append(Countries(countryName: "Turkmenistan", imageName: "tm"))
        flagsLevel8.append(Countries(countryName: "Dominica", imageName: "dm"))
        flagsLevel8.append(Countries(countryName: "Eswatini ", imageName: "sz"))
        flagsLevel8.append(Countries(countryName: "Gambia", imageName: "gm"))
        flagsLevel8.append(Countries(countryName: "Guyana", imageName: "gy"))
        flagsLevel8.append(Countries(countryName: "Laos", imageName: "la"))
        flagsLevel8.append(Countries(countryName: "Malawi", imageName: "mw"))
        flagsLevel8.append(Countries(countryName: "Maldives", imageName: "mv"))
        flagsLevel8.append(Countries(countryName: "Montenegro", imageName: "me"))
        flagsLevel8.append(Countries(countryName: "Somalia", imageName: "so"))
        flagsLevel8.append(Countries(countryName: "Tuvalu", imageName: "tv"))
        
        flagsLevel9.append(Countries(countryName: "Tajikistan", imageName: "tj"))
        flagsLevel9.append(Countries(countryName: "Tonga", imageName: "to"))
        flagsLevel9.append(Countries(countryName: "Solomon Islands", imageName: "sb"))
        flagsLevel9.append(Countries(countryName: "Sierra Leone", imageName: "sl"))
        flagsLevel9.append(Countries(countryName: "Seychelles", imageName: "sc"))
        flagsLevel9.append(Countries(countryName: "San Marino", imageName: "sm"))
        flagsLevel9.append(Countries(countryName: "Saint Lucia", imageName: "lc"))
        flagsLevel9.append(Countries(countryName: "Rwanda", imageName: "rw"))
        flagsLevel9.append(Countries(countryName: "Nauru", imageName: "nr"))
        flagsLevel9.append(Countries(countryName: "Mozambique", imageName: "mz"))
        flagsLevel9.append(Countries(countryName: "Micronesia", imageName: "fm"))
        flagsLevel9.append(Countries(countryName: "Mauritius", imageName: "mu"))
        flagsLevel9.append(Countries(countryName: "Lesotho", imageName: "ls"))
        flagsLevel9.append(Countries(countryName: "Grenada", imageName: "gd"))
        flagsLevel9.append(Countries(countryName: "East Timor", imageName: "tl"))
        flagsLevel9.append(Countries(countryName: "Eritrea", imageName: "er"))
        flagsLevel9.append(Countries(countryName: "Burkina Faso", imageName: "bf"))
        flagsLevel9.append(Countries(countryName: "Benin", imageName: "bj"))
        flagsLevel9.append(Countries(countryName: "Antigua and Barbuda", imageName: "ag"))
        flagsLevel9.append(Countries(countryName: "Guatemala", imageName: "gt"))
        
        flagsLevel10.append(Countries(countryName: "Guinea-Bissau", imageName: "gw"))
        flagsLevel10.append(Countries(countryName: "Marshall Islands", imageName: "mh"))
        flagsLevel10.append(Countries(countryName: "Nepal", imageName: "np"))
        flagsLevel10.append(Countries(countryName: "Saint Kitts and Nevis", imageName: "kn"))
        flagsLevel10.append(Countries(countryName: "Saint Vincent and the Grenadines", imageName: "vc"))
        flagsLevel10.append(Countries(countryName: "São Tomé and Príncipe", imageName: "st"))
        flagsLevel10.append(Countries(countryName: "Cabo Verde", imageName: "cv"))
        flagsLevel10.append(Countries(countryName: "Myanmar", imageName: "mm-1"))
        flagsLevel10.append(Countries(countryName: "Mauritania", imageName: "mr"))
        flagsLevel10.append(Countries(countryName: "Vanuatu", imageName: "vu"))
        flagsLevel10.append(Countries(countryName: "Belize", imageName: "bz"))
        flagsLevel10.append(Countries(countryName: "Cook Islands", imageName: "ck"))
        flagsLevel10.append(Countries(countryName: "Niue", imageName: "nu"))
        flagsLevel10.append(Countries(countryName: "England", imageName: "en"))
        flagsLevel10.append(Countries(countryName: "Wales", imageName: "wales"))
        flagsLevel10.append(Countries(countryName: "Estonia", imageName: "ee"))
        flagsLevel10.append(Countries(countryName: "Kosovo", imageName: "ks"))
        flagsLevel10.append(Countries(countryName: "Palau", imageName: "pw"))
        flagsLevel10.append(Countries(countryName: "Ivory Coast", imageName: "ci"))
        flagsLevel10.append(Countries(countryName: "Comoros", imageName: "km"))
        
        
        
        
        flagsBank.append(flagsLevel1)
        flagsBank.append(flagsLevel2)
        flagsBank.append(flagsLevel3)
        flagsBank.append(flagsLevel4)
        flagsBank.append(flagsLevel5)
        flagsBank.append(flagsLevel6)
        flagsBank.append(flagsLevel7)
        flagsBank.append(flagsLevel8)
        flagsBank.append(flagsLevel9)
        flagsBank.append(flagsLevel10)
        
    }
}
